---
- name: Apply Kubernetes manifests individually
  hosts: localhost
  remote_user: mohitgupta0205
  become: false
  environment:
    KUBECONFIG: /home/mohitgupta0205/.kube/config
  roles:
    - database
    - pgadmin
    - patient_service
    - doctor_service
    - appointment_service
    - gateway
    - monitoring
    - tracing
    - hpa
