---
- name: Apply Prometheus manifest
  command: kubectl apply -f {{ playbook_dir }}/kubernetes/k8s/prometheus.yaml

- name: Apply Grafana manifest
  command: kubectl apply -f {{ playbook_dir }}/kubernetes/k8s/grafana.yaml